### PR TITLE
SRVKE-470 - use hardcoded image for eventing upgrade

### PR DESCRIPTION
**Pull request by aliok**
https://issues.redhat.com/browse/SRVKE-470

## Proposed Changes

* Add harcoded image for eventing upgrade job

### CODE REVIEW

**Comment by aliok** [comment]
/hold 
hold for @warrenvw 

@warrenvw, we just merge this and trigger a new build to overwrite the existing image, right?
then we don't need to do anything on serverless operator.

**Comment by warrenvw** [comment]
Ideally, the change is made in the serverless-operator CSV so that no additional feature requests need to be added to the CPaaS backlog. Such a request could block our migration to CPaaS.

Having said that, I see no issue making the change in our existing productization pipeline.

**Comment by aliok** [comment]
/unhold

Thanks @warrenvw

**Pull request merged**
